[redis]
ipaddress = "localhost"
port = "6379"
password = ""
DB = 0

[threshold]
# exceed by exec sudo ping <IP> -i 0.00005 -c 1000 -s 1000
interval = 5
min = 1000000

[collectd]
plugin = "barometer-localagent"
type = "if-octets-threshold"
