[redis]
ipaddress = "localhost"
#port = 6379
password = ""
DB = 0
host = "localhost"
port = "6379"
#password = ""
#db = 0

[amqp]
host = "192.168.0.34"
user = "stackrabbit"
password = "stackqueue"
port = "5672"

[collectd]
confdir = "/etc/collectd/collectd.conf.d/"
